package com.sdyx.boss.service.internal.customer.echannel.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IUnifiedEChannelService", targetNamespace = "http://impl.webservice.echannel.customer.internal.service.boss.sdyx.com/")
public interface IUnifiedEChannelService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "doRequest", targetNamespace = "http://impl.webservice.echannel.customer.internal.service.boss.sdyx.com/", className = "com.sdyx.boss.service.internal.customer.echannel.webservice.impl.DoRequest")
	@ResponseWrapper(localName = "doRequestResponse", targetNamespace = "http://impl.webservice.echannel.customer.internal.service.boss.sdyx.com/", className = "com.sdyx.boss.service.internal.customer.echannel.webservice.impl.DoRequestResponse")
	public String doRequest(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
