package com.sysway.boss.service.internal.customer.echannel;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.huge.iunifiedechannelservice.BillInfo;
import com.huge.iunifiedechannelservice.CallResultInfo;
import com.huge.iunifiedechannelservice.CommonTradeInfo;
import com.huge.iunifiedechannelservice.CustomerBalanceInfo;
import com.huge.iunifiedechannelservice.CustomerInfo;
import com.huge.iunifiedechannelservice.ExternalTradeCheckingInfo;
import com.huge.iunifiedechannelservice.RechargeInfo;
import com.huge.iunifiedechannelservice.TerminalInfo;
import com.huge.iunifiedechannelservice.ValueAddedProductInfo;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IUnifiedEChannelService", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
public interface IUnifiedEChannelService {

	/**
	 * 
	 * @param commonTradeInfo
	 * @param terminalIdentification
	 * @return returns com.huge.iunifiedechannelservice.
	 *         FindPhysicalResourceInfoResponseWrapper.PhysicalResourceInfos
	 */
	@WebMethod(action = "findPhysicalResourceInfo")
	@WebResult(name = "physicalResourceInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "findPhysicalResourceInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindPhysicalResourceInfo")
	@ResponseWrapper(localName = "findPhysicalResourceInfoResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindPhysicalResourceInfoResponseWrapper")
	public com.huge.iunifiedechannelservice.FindPhysicalResourceInfoResponseWrapper.PhysicalResourceInfos findPhysicalResourceInfo(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "terminalIdentification", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String terminalIdentification);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param bookingDate
	 * @param rechargeInfo
	 * @param customerCode
	 * @param purchaseInfos
	 * @return returns com.huge.iunifiedechannelservice.CallResultInfo
	 */
	@WebMethod(action = "checkPurchaseExclusiveBalanceProduct")
	@WebResult(name = "callResultInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "checkPurchaseExclusiveBalanceProduct", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.CheckPurchaseExclusiveBalanceProduct")
	@ResponseWrapper(localName = "checkPurchaseExclusiveBalanceProductResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.CheckPurchaseExclusiveBalanceProductResponse")
	public CallResultInfo checkPurchaseExclusiveBalanceProduct(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode,
			@WebParam(name = "bookingDate", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String bookingDate,
			@WebParam(name = "purchaseInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") com.huge.iunifiedechannelservice.CheckPurchaseExclusiveBalanceProduct.PurchaseInfos purchaseInfos,
			@WebParam(name = "rechargeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") RechargeInfo rechargeInfo);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param customerCode
	 * @return returns
	 *         com.huge.iunifiedechannelservice.FindMarketingPlanInfoResponseWrapper
	 *         .MarketingPlanInfos
	 */
	@WebMethod(action = "findMarketPlanInfo")
	@WebResult(name = "marketingPlanInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "findMarketPlanInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindMarketPlanInfo")
	@ResponseWrapper(localName = "findMarketPlanInfoResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindMarketingPlanInfoResponseWrapper")
	public com.huge.iunifiedechannelservice.FindMarketingPlanInfoResponseWrapper.MarketingPlanInfos findMarketPlanInfo(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param customerCode
	 * @return returns
	 *         java.util.List<com.huge.iunifiedechannelservice.TerminalInfo>
	 */
	@WebMethod(action = "findTerminalInfo")
	@WebResult(name = "terminalInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "findTerminalInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindTerminalInfo")
	@ResponseWrapper(localName = "findTerminalInfoResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindTerminalInfoResponse")
	public List<TerminalInfo> findTerminalInfo(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode);

	/**
	 * 
	 * @param startDate
	 * @param commonTradeInfo
	 * @param customerCode
	 * @param endDate
	 * @return returns java.util.List<com.huge.iunifiedechannelservice.BillInfo>
	 */
	@WebMethod(action = "findBillInfo")
	@WebResult(name = "billInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "findBillInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindBillInfo")
	@ResponseWrapper(localName = "findBillInfoResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindBillInfoResponse")
	public List<BillInfo> findBillInfo(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode,
			@WebParam(name = "startDate", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String startDate,
			@WebParam(name = "endDate", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String endDate);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param customerCode
	 * @return returns
	 *         java.util.List<com.huge.iunifiedechannelservice.CustomerBalanceInfo
	 *         >
	 */
	@WebMethod(action = "findCustomerBalanceInfo")
	@WebResult(name = "customerBalanceInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "findCustomerBalanceInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindCustomerBalanceInfo")
	@ResponseWrapper(localName = "findCustomerBalanceInfoResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindCustomerBalanceInfoResponse")
	public List<CustomerBalanceInfo> findCustomerBalanceInfo(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param externalTradeCheckingInfo
	 * @return returns com.huge.iunifiedechannelservice.CallResultInfo
	 */
	@WebMethod(action = "check")
	@WebResult(name = "checkResult", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "check", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.Check")
	@ResponseWrapper(localName = "checkResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.CheckResponse")
	public CallResultInfo check(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "externalTradeCheckingInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") ExternalTradeCheckingInfo externalTradeCheckingInfo);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param terminalIdentification
	 * @param productOfferingCode
	 * @return returns com.huge.iunifiedechannelservice.CallResultInfo
	 */
	@WebMethod(action = "isCanPurchase")
	@WebResult(name = "callResult", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "isCanPurchase", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.IsCanPurchase")
	@ResponseWrapper(localName = "isCanPurchaseResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.IsCanPurchaseResponse")
	public CallResultInfo isCanPurchase(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "terminalIdentification", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String terminalIdentification,
			@WebParam(name = "productOfferingCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String productOfferingCode);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param customerIdentification
	 * @param customerIdentificationType
	 * @return returns com.huge.iunifiedechannelservice.CustomerInfo
	 */
	@WebMethod(action = "findCustomerInfo")
	@WebResult(name = "customerInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "findCustomerInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindCustomerInfo")
	@ResponseWrapper(localName = "findCustomerInfoResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindCustomerInfoResponse")
	public CustomerInfo findCustomerInfo(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerIdentification", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerIdentification,
			@WebParam(name = "customerIdentificationType", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") int customerIdentificationType);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param bookingDate
	 * @param customerCode
	 * @param purchaseInfos
	 * @return returns com.huge.iunifiedechannelservice.CallResultInfo
	 */
	@WebMethod(action = "purchase")
	@WebResult(name = "callResult", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "purchase", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.Purchase")
	@ResponseWrapper(localName = "purchaseResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.PurchaseResponse")
	public CallResultInfo purchase(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode,
			@WebParam(name = "bookingDate", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String bookingDate,
			@WebParam(name = "purchaseInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") com.huge.iunifiedechannelservice.Purchase.PurchaseInfos purchaseInfos);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param rechargeInfo
	 * @param customerCode
	 * @return returns com.huge.iunifiedechannelservice.CallResultInfo
	 */
	@WebMethod(action = "recharge")
	@WebResult(name = "callResult", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "recharge", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.Recharge")
	@ResponseWrapper(localName = "rechargeResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.RechargeResponse")
	public CallResultInfo recharge(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode,
			@WebParam(name = "rechargeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") RechargeInfo rechargeInfo);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param terminalIdentification
	 * @param customerCode
	 * @return returns
	 *         com.huge.iunifiedechannelservice.FindProductOfferingInfoResponseWrapper
	 *         .ProductOfferingInfos
	 */
	@WebMethod(action = "findProductOfferingInfo")
	@WebResult(name = "productOfferingInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "findProductOfferingInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindProductOfferingInfo")
	@ResponseWrapper(localName = "findProductOfferingInfoResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindProductOfferingInfoResponseWrapper")
	public com.huge.iunifiedechannelservice.FindProductOfferingInfoResponseWrapper.ProductOfferingInfos findProductOfferingInfo(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode,
			@WebParam(name = "terminalIdentification", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String terminalIdentification);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param bookingDate
	 * @param rechargeInfo
	 * @param customerCode
	 * @param purchaseInfos
	 * @return returns com.huge.iunifiedechannelservice.CallResultInfo
	 */
	@WebMethod(action = "purchaseExclusiveBalanceProduct")
	@WebResult(name = "callResultInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "purchaseExclusiveBalanceProduct", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.PurchaseExclusiveBalanceProduct")
	@ResponseWrapper(localName = "purchaseExclusiveBalanceProductResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.PurchaseExclusiveBalanceProductResponse")
	public CallResultInfo purchaseExclusiveBalanceProduct(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode,
			@WebParam(name = "bookingDate", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String bookingDate,
			@WebParam(name = "purchaseInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") com.huge.iunifiedechannelservice.PurchaseExclusiveBalanceProduct.PurchaseInfos purchaseInfos,
			@WebParam(name = "rechargeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") RechargeInfo rechargeInfo);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param terminalIdentification
	 * @param customerCode
	 * @return returns
	 *         java.util.List<com.huge.iunifiedechannelservice.ValueAddedProductInfo
	 *         >
	 */
	@WebMethod(action = "findValueAddedProductInfo")
	@WebResult(name = "valueAddedProductInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "findValueAddedProductInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindValueAddedProductInfo")
	@ResponseWrapper(localName = "findValueAddedProductInfoResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindValueAddedProductInfoResponse")
	public List<ValueAddedProductInfo> findValueAddedProductInfo(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode,
			@WebParam(name = "terminalIdentification", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String terminalIdentification);

	/**
	 * 
	 * @param startDate
	 * @param commonTradeInfo
	 * @param customerCode
	 * @param endDate
	 * @return returns
	 *         com.huge.iunifiedechannelservice.FindVodInfoResponseWrapper
	 *         .VodInfos
	 */
	@WebMethod(action = "findVodInfo")
	@WebResult(name = "vodInfos", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "findVodInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindVodInfo")
	@ResponseWrapper(localName = "findVodInfoResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.FindVodInfoResponseWrapper")
	public com.huge.iunifiedechannelservice.FindVodInfoResponseWrapper.VodInfos findVodInfo(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode,
			@WebParam(name = "startDate", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String startDate,
			@WebParam(name = "endDate", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String endDate);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param newPassword
	 * @param customerCode
	 * @param oldPassword
	 * @return returns com.huge.iunifiedechannelservice.CallResultInfo
	 */
	@WebMethod(action = "modifyServicePassword")
	@WebResult(name = "callResult", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "modifyServicePassword", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.ModifyServicePassword")
	@ResponseWrapper(localName = "modifyServicePasswordResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.ModifyServicePasswordResponse")
	public CallResultInfo modifyServicePassword(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode,
			@WebParam(name = "oldPassword", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String oldPassword,
			@WebParam(name = "newPassword", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String newPassword);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param smartCardNo
	 * @param customerCode
	 * @return returns com.huge.iunifiedechannelservice.CallResultInfo
	 */
	@WebMethod(action = "openInteractionAccount")
	@WebResult(name = "callResult", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "openInteractionAccount", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.OpenInteractionAccount")
	@ResponseWrapper(localName = "openInteractionAccountResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.OpenInteractionAccountResponse")
	public CallResultInfo openInteractionAccount(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerCode", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerCode,
			@WebParam(name = "smartCardNo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String smartCardNo);

	/**
	 * 
	 * @param commonTradeInfo
	 * @param servicePassword
	 * @param customerIdentification
	 * @param identifyType
	 * @return returns com.huge.iunifiedechannelservice.CallResultInfo
	 */
	@WebMethod(action = "login")
	@WebResult(name = "callResult", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/")
	@RequestWrapper(localName = "login", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.Login")
	@ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/", className = "com.huge.iunifiedechannelservice.LoginResponse")
	public CallResultInfo login(
			@WebParam(name = "commonTradeInfo", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") CommonTradeInfo commonTradeInfo,
			@WebParam(name = "customerIdentification", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String customerIdentification,
			@WebParam(name = "identifyType", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String identifyType,
			@WebParam(name = "servicePassword", targetNamespace = "http://www.huge.com/IUnifiedEChannelService/") String servicePassword);

}
