package com.sysway.boss.service.internal.customer.echannel;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UnifiedEChannelServiceService service = new UnifiedEChannelServiceService();
 * IUnifiedEChannelService portType = service.getUnifiedEChannelServicePort();
 * portType.findPhysicalResourceInfo(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UnifiedEChannelServiceService", targetNamespace = "http://echannel.customer.internal.service.boss.sysway.com/", wsdlLocation = "http://9.6.0.192:8689/sysway-boss-service/cxf/IUnifiedEChannelService?wsdl")
public class UnifiedEChannelServiceService extends Service {

	private final static URL UNIFIEDECHANNELSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.sysway.boss.service.internal.customer.echannel.UnifiedEChannelServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.sysway.boss.service.internal.customer.echannel.UnifiedEChannelServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://9.6.0.164:8086/sysway-boss-service/cxf/IUnifiedEChannelService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://9.6.0.192:8689/sysway-boss-service/cxf/IUnifiedEChannelService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		UNIFIEDECHANNELSERVICESERVICE_WSDL_LOCATION = url;
	}

	public UnifiedEChannelServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UnifiedEChannelServiceService() {
		super(UNIFIEDECHANNELSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://echannel.customer.internal.service.boss.sysway.com/",
				"UnifiedEChannelServiceService"));
	}

	/**
	 * 
	 * @return returns IUnifiedEChannelService
	 */
	@WebEndpoint(name = "UnifiedEChannelServicePort")
	public IUnifiedEChannelService getUnifiedEChannelServicePort() {
		return super.getPort(new QName(
				"http://echannel.customer.internal.service.boss.sysway.com/",
				"UnifiedEChannelServicePort"), IUnifiedEChannelService.class);
	}

}
